const fs = require('fs');
let h = fs.readFileSync('plantglow/index-zh.html', 'utf8');

// Complete tip translations
const allTranslations = {
  'Can survive months without watering': '可以數月不澆水',
  'Dropping leaves usually means stress from relocation': '落葉通常表示移位壓力',
  'Wipe leaves to remove dust': '擦拭葉子去除灰塵',
  'Produces dangling babies': '產生垂吊的小植株',
  'Easy to propagate - just pot the babies': '容易繁殖 — 只需將小植株盆栽',
  'Tolerates a range of conditions': '耐受各種條件',
  'Brown tips from fluoride - use filtered water': '氟化物導致褐色尖端 — 使用過濾水',
  'Great air purifier (NASA study)': '出色的空氣淨化器（NASA 研究）',
  'Wipe leaves monthly to keep them shiny': '每月擦拭葉子保持光亮',
  'Slow growing but virtually indestructible': '生長緩慢但幾乎不死',
  'Loves bright, direct sunlight - perfect for sunny windowsills': '喜歡明亮的直射光 — 非常適合朝南窗台',
  'Let soil dry COMPLETELY between waterings': '澆水之間讓土壤完全乾燥',
  'Produces pups (baby plants) that can be separated': '產生可以分開的新芽',
  'Use terracotta pots for better drainage': '使用陶罐更好的排水',
  'Prune to maintain compact shape': '修剪以保持緊湊形狀',
  'Leaves should be firm and plump when healthy': '健康時葉子應該堅實飽滿',
  'Red edges develop with bright light exposure': '明亮光線下葉緣變紅',
  'Leaves move throughout the day following light': '葉子整天隨光線移動',
  'Use filtered or rainwater to avoid fluoride': '使用過濾水或雨水避免氟化物',
  'Loves humidity - perfect for bathrooms': '喜歡濕度 — 非常適合浴室',
  'Leaves fold up at night': '葉子在夜間折叠',
  'Needs several years before producing flowers': '需要數年才能开花',
  'Split leaves are normal, not a problem': '裂葉是正常的，不是問題',
  'Grows large - needs space to spread': '生長大型 — 需要空間伸展',
  'Outdoor plants can reach 6-10 feet': '户外植物可達 2-3 公尺',
  'Wipe leaves regularly to keep them shiny': '定期擦拭葉子保持光亮',
  'Start with dark green variety if new to plant care': '如果新手照顧植物，從深綠色品種開始',
  'Can grow 6-8 feet indoors with good care': '照顧得當室內可達 2-2.5 公尺',
  'Milky sap can irritate skin - wear gloves when pruning': '乳白色汁液可能刺激皮膚 — 修剪時戴手套',
  'Rotate quarterly for even growth': '每季旋轉以均勻生長',
  'Water with ice cubes for easy, measured watering': '用冰塊澆水，方便測量水量',
  'Roots turn silver when dry, green when moist': '根乾燥時變銀色，濕潤時變綠色',
  'After flowers fall, cut stem above a node to rebloom': '花落後，在節點上方切莖以再次开花',
  'Transparent pots help you monitor root health': '透明盆幫助監測根系健康',
  'Never let water sit in the crown (center)': '千萬別讓水積在冠部（中心）',
  'One of the best low-light plants available': '最好的低光植物之一',
  'Allow soil to dry between waterings': '澆水之間讓土壤乾燥',
  'Variegated types need more light': '斑葉品種需要更多光照',
  'Excellent air purifier (NASA study)': '出色的空氣淨化器（NASA 研究）',
  'Slow growing but very long-lived': '生長緩慢但非常長壽',
  'Tall, dramatic plant with spiky leaves': '高大戲劇性的尖葉植物',
  'Sensitive to fluoride - use filtered water': '對氟化物敏感 — 使用過濾水',
  'Brown tips are common and usually harmless': '褐色尖端常見，通常無害',
  'Can grow 6 feet or more indoors': '室內可達 2 公尺以上',
  'Leaves have red or pink margins on some varieties': '有些品種葉緣紅色或粉紅色',
  'Grows vigorously - great for beginners': '生長旺盛 — 非常適合新手',
  'Harvest regularly to prevent flowering': '定期收穫以防止开花',
  'Loves moist soil but hates waterlogged roots': '喜歡濕潤土壤但讨厌积水根',
  'Can be grown in water alone indefinitely': '可以只用水永久種植',
  'Spearmint and peppermint are easiest varieties': '留蘭香和薄荷是最容易的品種',
  'Needs at least 6 hours of direct sunlight': '需要至少 6 小時直射陽光',
  'Pinch off flowers to keep leaves growing': '摘掉花朵以保持葉子生長',
  'Harvest from the top to encourage bushiness': '從頂部收穫以促進茂盛',
  'Loves heat - wait until nights are warm to transplant': '喜歡溫暖 — 等到晚間溫暖再移植',
  'Genovese basil is best for pesto': '熱那亞羅勒最適合做青醬',
  'Prefers well-drained soil': '喜歡排水良好的土壤',
  'Prune after flowering to maintain shape': '开花後修剪保持形狀',
  'Rosemary thrives in similar conditions': '迷迭香在類似條件下生長良好',
  'Great for aromatic gardens': '非常適合香草花園',
  'Delicate trailing succulent with heart-shaped leaves': '精緻的垂吊多肉，心形葉片',
  'Beautiful in hanging baskets': '美麗的吊籃植物',
  'Easily propagated from stem cuttings': '容易從莖插繁殖',
  'Goes semi-dormant in winter - water less': '冬季半休眠 — 少澆水',
  'Pancake-shaped leaves on long petioles': '長葉柄上的煎餅形葉片',
  'Rotate regularly for even growth': '定期旋轉均勻生長',
  'Produces many babies you can propagate': '產生許多可以繁殖的小植株',
  'Fun, quirky plant perfect for Instagram': '有趣古怪的植物，非常適合 Instagram',
  'Loves a humid environment but adaptable': '喜歡潮濕環境但適應性強',
  'Classic Victorian-era houseplant': '經典維多利亞時代室內植物',
  'Mist daily or use a pebble tray': '每天噴霧或使用鵝卵石托盤',
  'Perfect for bathrooms with high humidity': '非常適合高濕度浴室',
  'Fronds can grow up to 3 feet long': '葉子可達 90 公分長',
  'Brown fronds at the base are normal - trim them': '底部褐色葉子正常 — 可以修剪',
  'Versatile trailing or climbing plant': '多功能的垂吊或攀爬植物',
  'Great for topiaries and hanging baskets': '非常適合造型植物和吊籃',
  'Prefers cooler temperatures': '喜歡較涼的溫度',
  'Keep soil evenly moist': '保持土壤均勻濕潤',
  'Compact blooming plant for small spaces': '適合小空間的緊湊开花植物',
  'Deadhead spent flowers to encourage more blooms': '摘除凋謝花朵促進更多开花',
  'Tolerates lower light better than most bloomers': '比大多数开花植物更耐低光',
  'Available in purple, pink, white, and variegated': '有紫色、粉紅色、白色和斑葉品種',
  'Elegant palm perfect for corner spots': '優雅的棕櫚，適合角落位置',
  'Loves humidity - mist daily or use a humidifier': '喜歡濕度 — 每天噴霧或使用加濕器',
  'Difficult but rewarding indoor palm': '困難但值得的室內棕櫚',
  'Fronds turn yellow when thirsty': '缺水時葉子變黃',
  'Not a true palm - succulent related to yucca': '不是真正的棕櫚 — 是與絲蘭相關的多肉植物',
  'Bulbous trunk stores water': '球莖儲存水分',
  'Needs as much light as possible': '需要盡可能多的光照',
  'Also called Dumb Cane - sap is irritating': '也稱為啞藤 — 汁液刺激',
  'Large patterned leaves add tropical vibes': '大圖案葉片增添熱帶風情',
  'Easy beginner-friendly houseplant': '容易的新手友好室內植物',
  'Keep soil moderately moist': '保持土壤適度濕潤',
  'Vivid red, orange, and yellow foliage': '鮮紅、橙色和黃色葉片',
  'Needs lots of light to maintain color': '需要大量光照保持顏色',
  'Dropping leaves usually means temperature change': '落葉通常表示溫度變化',
  'Leaves fold up at night like praying hands': '葉子像祈禱的手一樣在夜間折叠',
  'Intricate patterned foliage in green and red': '綠色和紅色的複雜圖案葉片',
  'Loves humidity - perfect for kitchens and bathrooms': '喜歡濕度 — 非常適合廚房和浴室',
  'Non-toxic - safe for pets': '無毒 — 寵物安全',
  'Striking snake-shaped leaves with white bumps': '醒目的蛇形葉片帶白色突起',
  'Can tolerate lower light than most succulents': '比大多數多肉植物更耐低光',
  'Produces offsets that can be propagated': '產生可以繁殖的側芽',
  'Nearly impossible to kill - true to its name': '幾乎不可能死亡 — 名副其實',
  'Tolerates neglect, low light, and irregular watering': '耐受疏忽、低光照和不規律澆水',
  'Dark green strap-like leaves': '深綠色帶狀葉片',
  'Perfect for offices and low-light spots': '非常適合辦公室和低光位置',
  'Very slow growing but extremely long-lived': '生長非常緩慢但極其長壽',
  'Compact plant with fleshy, glossy leaves': '緊湊的植物，肉質有光澤葉片',
  'Perfect for small spaces and desks': '非常適合小空間和桌面',
  'Let top soil dry before watering': '澆水前讓表土乾燥',
  'Varieties include solid green, variegated, and ripple': '品種包括全綠、斑葉和波紋',
  'Trunk often braided for decorative appeal': '莖通常編辮以增加裝飾感',
  'Likes consistent moisture but not soggy soil': '喜歡持續濕潤但不積水土壤',
  'Can grow quite tall indoors': '室內可以長得相當高',
  'Keep away from cold drafts and heating vents': '遠離冷風和暖氣出口',
  'Palmate leaves spread like an umbrella': '掌狀葉片像傘一樣展開',
  'Easy growing - great for beginners': '容易種植 — 非常適合新手',
  'Can be trained as a tree or bushy shrub': '可以訓練成樹或灌木叢',
  'Trim to control height and encourage fullness': '修剪以控制高度並促進豐滿',
  'Drooping usually means it needs water': '下垂通常表示需要水',
  'Glossy heart-shaped flowers in red, pink, or white': '紅色、粉紅色或白色的光澤心形花朵',
  'Flowers last for weeks': '花朵持續數週',
  'Blooms beautiful flowers around Christmas time': '聖誕節前後開美麗的花',
  'Segmented stems cascade beautifully': '分段莖美麗地垂下',
  'Keep in a dark room for 6 weeks to trigger blooming': '放在黑暗房間 6 週以觸發开花',
  'Avoid moving once buds form - they fall easily': '花蕾形成後避免移動 — 它們容易掉落',
  'Easy to propagate from stem segments': '容易從莖段繁殖',
  'Prefers bright, indirect light — direct sun scorches leaves': '喜歡明亮散射光 — 直射光會燒傷葉子',
  'Keep soil consistently moist but never waterlogged': '保持土壤持續濕潤但不積水',
  'Loves humidity — mist regularly or use a pebble tray': '喜歡濕度 — 定期噴霧或使用鵝卵石托盤',
  'Wipe leaves monthly to keep them glossy and dust-free': '每月擦拭葉子保持光亮無灰塵',
  'Unique trailing succulent with pea-shaped leaves': '独特的垂吊多肉，豌豆形葉片',
  'Avoid direct afternoon sun': '避免下午直射陽光',
  'Goes semi-dormant in winter - water sparingly': '冬季半休眠 — 少量澆水',
  'Also called Wax Plant for its waxy leaves': '也因蠟質葉片稱為蠟植物',
  'Produces stunning ball-shaped flower clusters': '產生驚人的球形花簇',
  'Vibrant pink, red, or white spotted leaves': '充滿活力的粉紅色、紅色或白色斑點葉片',
  'Loves humidity - perfect for terrariums': '喜歡濕度 — 非常適合玻璃缸',
  'Pinch to encourage bushier growth': '摘心促進更茂盛的生長',
  'Can be grown outdoors in shade': '可以在户外陰涼處種植',
  'Nipping flowers helps leaves stay colorful': '摘除花朵有助於葉子保持色彩',
  'Victorian-era favorite, popular since the 1800s': '維多利亞時代的最愛，自 1800 年代流行',
  'Tolerates low light better than most palms': '比大多數棕櫚更耐低光',
  'Fronds grow in clusters from the base': '葉子從基部叢生',
  'Silver and purple striped leaves': '銀色和紫色條紋葉片',
  'Fast growing and easy to propagate': '生長快速且容易繁殖',
  'Pinch stems to encourage fuller growth': '摘除莖尖促進更豐滿的生長',
  'Can be moved outdoors for summer': '夏天可以移到户外',
  'Stunning veined leaves in pink, white, or red': '粉紅色、白色或紅色的驚人脈紋葉片',
  'Dramatic fainting when thirsty - bounces back with water': '缺水戲劇性枯萎 — 澆水後恢復',
  'Perfect for closed terrariums': '非常適合封閉玻璃缸',
  'Compact size great for desks and shelves': '緊湊尺寸非常適合桌面和架子',
  'Arrow-shaped leaves that mature over time': '隨時間成熟的箭形葉片',
  'Easy to grow and very adaptable': '容易種植且非常適應',
  'Can trail or climb with support': '可以垂吊或攀爬',
  'Many variegated varieties available': '有許多斑葉品種可供選擇',
  'Trailing succulent with plump, blue-green leaves': '垂吊多肉，豐滿藍綠色葉片',
  'Handle gently - leaves fall off easily': '輕柔處理 — 葉子容易掉落',
  'Needs bright light to maintain compact shape': '需要明亮光照保持緊湊形狀',
  'Delicate, dark burgundy serrated leaves': '精緻的深酒紅色鋸齒葉片',
  'Elegant architectural plant': '優雅的建築植物',
  'Slow growing but stunning specimen plant': '生長緩慢但令人驚艷的標本植物',
  'Beautiful winter-flowering plant': '美麗的冬季开花植物',
  'Cool temperatures extend blooming period': '涼爽溫度延長开花期',
  'Goes dormant in summer - reduce water': '夏季休眠 — 減少澆水',
  'Flowers in pink, red, white, and purple': '粉紅色、紅色、白色和紫色开花',
  'Holes in leaves give it the Swiss cheese nickname': '葉子上的孔洞給它瑞士起司的綽號',
  'More delicate than Monstera Deliciosa': '比龜背竹更嬌嫩',
  'Fenestrations develop with age and light': '葉窗隨時間和光照發育',
  'Classic round cactus with fierce spines': '經典圓形仙人掌，帶尖刺',
  'Needs as much sun as possible': '需要盡可能多的陽光',
  'Can live for over 100 years': '可以活超過 100 年',
  'Yellow or orange flowers bloom at the top': '黃色或橙色花在頂部开放',
  'Large, dramatic palmate leaves': '大型戲劇性的掌狀葉片',
  'Perfect for adding tropical drama indoors': '非常適合為室內增添熱帶風情',
  'Tolerates low light better than most tropicals': '比大多數熱帶植物更耐低光',
  'Can be grown outdoors in mild climates': '可以在溫和氣候的户外種植',
};

// Apply all translations
let translated = 0;
for (const [eng, zh] of Object.entries(allTranslations)) {
  if (h.includes(eng)) {
    h = h.split(eng).join(zh);
    translated++;
  }
}

fs.writeFileSync('plantglow/index-zh.html', h, 'utf8');
console.log('Translated', translated, 'tips out of', Object.keys(allTranslations).length);

// Check remaining
const h2 = fs.readFileSync('plantglow/index-zh.html', 'utf8');
console.log('Has remaining English tips:', h2.includes('Can survive months without watering'));
console.log('Has Chinese tips:', h2.includes('可以數月不澆水'));